const key='pressflow-data-v1';
const SUPABASE_URL='https://iverxxxbrcwsxaclgnby.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_uZuR1P2iEanTx35si3TUew_EyznzJ-V';
const TEMPORARY_EMPLOYEE_CODE='1234';
const cloud=window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let cloudReady=false,currentSession=null,syncTimer=null,workspaceChannel=null;
const defaultTools=[{name:'Gooseneck',category:'punch'},{name:'Hemming',category:'punch'},{name:'V-die 1/2 in',category:'die'},{name:'V-die 1 in',category:'die'}];
const seed={products:[
 {id:1,part:'BP-1042',name:'Mounting bracket',material:'Steel',tool:'V-die 1/2 in',qty:180,avg:2.8,due:'2026-09-10'},
 {id:2,part:'PX-8810',name:'Enclosure side panel',material:'Stainless steel',tool:'Gooseneck',qty:55,avg:6.2,due:'2026-09-11'},
 {id:3,part:'AL-2007',name:'Control box lid',material:'Aluminum',tool:'V-die 1 in',qty:120,avg:3.6,due:'2026-09-15'},
 {id:4,part:'BP-1058',name:'Angle support',material:'Steel',tool:'Hemming',qty:240,avg:1.9,due:'2026-09-18'},
 {id:5,part:'SS-4150',name:'Guard rail plate',material:'Stainless steel',tool:'V-die 1 in',qty:70,avg:5.1,due:'2026-09-20'}],
 presses:[
 {id:1,name:'Press 1',daily:420,maxLength:120,materials:['Steel','Aluminum'],tools:['V-die 1/2 in','V-die 1 in']},
 {id:2,name:'Press 2',daily:390,maxLength:144,materials:['Steel','Stainless steel'],tools:['Gooseneck','V-die 1 in']},
 {id:3,name:'Press 3',daily:450,maxLength:96,materials:['Aluminum','Steel'],tools:['V-die 1/2 in','Hemming','V-die 1 in']},
 {id:4,name:'Press 4',daily:360,maxLength:120,materials:['Stainless steel','Steel'],tools:['Gooseneck','Hemming']}],history:[],tooling:defaultTools,partLibrary:{}};
let data=JSON.parse(localStorage.getItem(key))||seed;
if(!Array.isArray(data.tooling))data.tooling=[...defaultTools];
data.tooling=data.tooling.map(t=>typeof t==='string'?{name:t,category:/die/i.test(t)?'die':'punch'}:t);
if(!data.partLibrary)data.partLibrary={};
if(!data.assemblies)data.assemblies={};
if(!data.uncodedProducts)data.uncodedProducts=[];
if(!data.uncodedAssemblies)data.uncodedAssemblies=[];
data.products.forEach(p=>{let oldTool=p.tool;if(!p.punch)p.punch=data.tooling.find(t=>t.category==='punch'&&t.name===oldTool)?.name||data.tooling.find(t=>t.category==='punch')?.name;if(!p.die)p.die=data.tooling.find(t=>t.category==='die'&&t.name===oldTool)?.name||data.tooling.find(t=>t.category==='die')?.name;if(!p.length)p.length=24;if(!data.partLibrary[p.part])data.partLibrary[p.part]={part:p.part,name:p.name,assembly:p.assembly||null,material:p.material,punch:p.punch,die:p.die,length:p.length,qty:p.qty,avg:p.avg}});
Object.values(data.partLibrary).forEach(p=>{if(!p.punch)p.punch=data.tooling.find(t=>t.category==='punch')?.name;if(!p.die)p.die=data.tooling.find(t=>t.category==='die')?.name;if(!p.length)p.length=24});
data.presses.forEach(p=>{if(!p.maxLength)p.maxLength=120});
data.presses.forEach(press=>['punch','die'].forEach(category=>{if(!press.tools.some(name=>data.tooling.find(t=>t.name===name)?.category===category)){let tool=data.tooling.find(t=>t.category===category)?.name;if(tool)press.tools.push(tool)}}));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(key,JSON.stringify(data));if(cloudReady){clearTimeout(syncTimer);syncTimer=setTimeout(syncWorkspace,650)}} function hours(min){return `${(min/60).toFixed(1)} hr`} function est(p){return p.qty*p.avg}
function printPress(id){let press=data.presses.find(p=>p.id===id),list=plan().loads[id],used=list.reduce((n,a)=>n+a.minutes,0),w=window.open('','_blank','width=850,height=700');if(!w)return;w.document.write(`<!doctype html><html><head><title>${press.name} checklist</title><style>body{font-family:Arial,sans-serif;color:#102a43;margin:36px}h1{margin:0}p{color:#526b80}.meta{border-top:2px solid #126db5;border-bottom:1px solid #cbddeb;padding:12px 0;margin:18px 0;font-size:14px}table{width:100%;border-collapse:collapse}th{text-align:left;background:#eaf5ff;color:#0a3f6b;padding:10px;font-size:12px}td{border-bottom:1px solid #d8e5f0;padding:13px 10px;font-size:13px}.check{width:28px;height:28px;border:2px solid #126db5;border-radius:4px}.assembly{font-weight:bold;color:#126db5}@media print{body{margin:18px}}</style></head><body><h1>Press Flow — ${press.name}</h1><p>A+J Design LLC · Production checklist</p><div class="meta"><b>Scheduled work:</b> ${hours(used)} &nbsp; | &nbsp; <b>Allowed daily run time:</b> ${hours(press.daily)} &nbsp; | &nbsp; <b>Printed:</b> ${new Date().toLocaleDateString()}</div><table><thead><tr><th>Done</th><th>Part number</th><th>Assembly number</th><th>Product</th><th>Quantity</th><th>Punch / die</th><th>Est. time</th></tr></thead><tbody>${list.map(a=>`<tr><td><div class="check"></div></td><td>${a.product.part}</td><td class="assembly">${a.product.assembly||'Individual part'}</td><td>${a.product.name}</td><td>${a.product.qty}</td><td>${a.product.punch} / ${a.product.die}</td><td>${hours(a.minutes)}</td></tr>`).join('')||'<tr><td colspan="7">No assignments scheduled.</td></tr>'}</tbody></table></body></html>`);w.document.close();w.focus();w.print()}
function today(){return new Date('2026-09-08T12:00:00')} function daysUntil(date){return Math.ceil((new Date(date+'T12:00:00')-today())/86400000)}
function status(p){let d=daysUntil(p.due);return d<=2?'Due soon':d<=7?'This week':'Upcoming'}
function compatible(p,press){return p.length<=press.maxLength&&press.materials.includes(p.material)&&press.tools.includes(p.punch)&&press.tools.includes(p.die)}
function plan(){let loads=Object.fromEntries(data.presses.map(p=>[p.id,[]]));let un=[];[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).forEach(product=>{let compatiblePresses=data.presses.filter(press=>compatible(product,press)).map(press=>{let list=loads[press.id],used=list.reduce((n,a)=>n+a.minutes,0),last=list.at(-1)?.product,grouped=product.assembly&&list.some(a=>a.product.assembly===product.assembly),sameSetup=last&&last.punch===product.punch&&last.die===product.die,similarLength=last&&product.length<=last.length;return {press,used,score:used/press.daily-(grouped?0.18:0)-(sameSetup?0.16:0)-(sameSetup&&similarLength?0.08:0)}}).sort((a,b)=>a.score-b.score);if(!compatiblePresses.length){un.push({product,reason:'No compatible press'});return}let best=compatiblePresses.find(candidate=>candidate.used+est(product)<=candidate.press.daily);if(!best){un.push({product,reason:'Deferred — later due date than work already scheduled'});return}loads[best.press.id].push({product,minutes:est(product),over:false})});return {loads,un}}
function weekDays(){let d=new Date(today());d.setDate(d.getDate()-((d.getDay()+6)%7));return Array.from({length:5},(_,i)=>{let x=new Date(d);x.setDate(d.getDate()+i);return x})}function dateKey(d){return d.toISOString().slice(0,10)}function weeklyPlan(){let days=weekDays(),slots=[];days.forEach(day=>data.presses.forEach(press=>slots.push({day,press,used:0,jobs:[]})));let deferred=[];[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).forEach(product=>{let remaining=est(product);while(remaining>.01){let choices=slots.filter(slot=>compatible(product,slot.press)&&slot.used<slot.press.daily).sort((a,b)=>(a.used/a.press.daily)-(b.used/b.press.daily));if(!choices.length){deferred.push({product,minutes:remaining});break}let slot=choices[0],minutes=Math.min(remaining,slot.press.daily-slot.used);slot.jobs.push({product,minutes});slot.used+=minutes;remaining-=minutes}});return {days,slots,deferred}}
function renderWeekly(){let weekly=weeklyPlan();$('#weekly-schedule').innerHTML=weekly.days.map(day=>`<article class="panel"><div class="panel-title"><div><p class="eyebrow">${day.toLocaleDateString(undefined,{weekday:'long'}).toUpperCase()}</p><h2>${day.toLocaleDateString(undefined,{month:'short',day:'numeric'})}</h2></div></div><div class="table-wrap"><table><thead><tr><th>Press</th><th>Product / part</th><th>Assembly</th><th>Estimated time</th></tr></thead><tbody>${data.presses.map(press=>{let slot=weekly.slots.find(s=>s.day.getTime()===day.getTime()&&s.press.id===press.id);return slot.jobs.length?slot.jobs.map((job,i)=>`<tr><td>${i?'' : press.name}</td><td><b>${job.product.name}</b><br><span class="part">${job.product.part}</span></td><td>${job.product.assembly||'Individual'}</td><td>${hours(job.minutes)} / ${hours(press.daily)}</td></tr>`).join(''):`<tr><td>${press.name}</td><td colspan="3" class="part">Available</td></tr>`}).join('')}</tbody></table></div></article>`).join('')+(weekly.deferred.length?`<article class="panel unassigned"><div class="panel-title"><div><p class="eyebrow">REVIEW</p><h2>Work beyond this week</h2></div></div>${weekly.deferred.map(item=>`<div class="assignment"><b>${item.product.name}</b><div class="assignment-meta">${item.product.part} · ${hours(item.minutes)} remaining</div></div>`).join('')}</article>`:'')}
function renderCapacity(){let days=Math.max(1,+$('#planning-days').value||5),weekly=weeklyPlan(),required=Object.fromEntries(data.presses.map(p=>[p.id,0]));weekly.slots.forEach(slot=>required[slot.press.id]+=slot.jobs.reduce((n,j)=>n+j.minutes,0));let active=data.presses.filter(p=>required[p.id]>0),full=active.filter(p=>required[p.id]>=p.daily*days*.95).length,partial=active.filter(p=>required[p.id]>0&&required[p.id]<p.daily*days*.95).length,total=data.products.reduce((n,p)=>n+est(p),0);$('#capacity-metrics').innerHTML=[['Weekly demand',hours(total),'all listed jobs'],['Presses required',active.length,`${full} near 100% · ${partial} partial`],['Deferred demand',hours(weekly.deferred.reduce((n,x)=>n+x.minutes,0)),'beyond weekly capacity'],['Planning window',`${days} days`,'available capacity']].map(m=>`<div class="metric"><div class="metric-value">${m[1]}</div><div class="metric-note">${m[0]} · ${m[2]}</div></div>`).join('');$('#capacity-table').innerHTML=data.presses.map(p=>{let available=p.daily*days,need=required[p.id],util=available?Math.round(need/available*100):0,rec=util>=95?'Run at 100%':util>=75?'Run near capacity':util>0?'Run part-time':'Not needed';return `<tr><td><b>${p.name}</b></td><td>${hours(available)}</td><td>${hours(need)}</td><td><span class="status ${util>100?'alert':''}">${util}%</span></td><td>${rec}</td></tr>`}).join('')}
function normalizeHeader(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]/g,'')}function importRows(rows){let added=0,updated=0,unknown=[];rows.forEach(row=>{let fields=Object.fromEntries(Object.entries(row).map(([k,v])=>[normalizeHeader(k),v])),part=String(fields.partnumber||fields.part||fields.itemnumber||'').trim().toUpperCase();if(!part)return;let template=data.partLibrary[part];if(!template){unknown.push(part);return}let due=fields.duedate||fields.duedateplanned||fields.promisedate||fields.deliverydate||'';if(typeof due==='number'&&window.XLSX)due=XLSX.SSF.format('yyyy-mm-dd',due);due=String(due).slice(0,10)||'2026-09-15';let qty=Number(fields.quantity||fields.qty||template.qty)||template.qty,existing=data.products.find(p=>p.part===part&&p.due===due);if(existing){existing.qty=qty;updated++}else{data.products.push({...template,id:Date.now()+added,due,qty,assembly:fields.assemblynumber||fields.assembly||template.assembly||null});added++}});save();$('#import-result').innerHTML=`<div class="history-row"><span><b>${added}</b> new jobs added · <b>${updated}</b> matching jobs updated</span><span class="part">Import complete</span></div>${unknown.length?`<div class="history-row"><span><b>Needs programming:</b> ${[...new Set(unknown)].join(', ')}</span><span class="part">${unknown.length} unknown</span></div>`:'<div class="history-row"><span>All imported part numbers matched the product library.</span></div>'}`;renderAll()}
function renderAll(){renderDashboard();renderProducts();renderAssemblies();renderTimes();renderTooling();renderPresses();renderSchedule();renderWeekly();renderCapacity();renderDue()}
function renderDashboard(){let p=plan(), assigned=Object.values(p.loads).flat().length, total=data.products.reduce((n,x)=>n+est(x),0), capacity=data.presses.reduce((n,x)=>n+x.daily,0), soon=data.products.filter(x=>daysUntil(x.due)<=7).length;$('#metrics').innerHTML=[['Open products',data.products.length,'ready to schedule'],['Estimated work',hours(total),'across all products'],['Daily capacity',hours(capacity),'four brake presses'],['Due within 7 days',soon,soon?'priority assignments':'no urgent work']].map(x=>`<div class="metric"><div class="metric-value">${x[1]}</div><div class="metric-note">${x[0]} · ${x[2]}</div></div>`).join('');$('#utilization').innerHTML=data.presses.map(press=>{let used=(p.loads[press.id]||[]).reduce((n,a)=>n+a.minutes,0),pct=Math.round(100*used/press.daily);return `<div class="progress-row"><span>${press.name}</span><div class="track"><div class="fill ${pct>100?'over':''}" style="width:${Math.min(pct,100)}%"></div></div><b>${pct}%</b></div>`}).join('');$('#due-soon').innerHTML=[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4).map(x=>`<div class="list-row"><span><b>${x.name}</b><br><span class="part">${x.part}</span></span><span class="due-tag ${daysUntil(x.due)<=2?'hot':''}">${daysUntil(x.due)}d · ${x.due.slice(5)}</span></div>`).join('');let assignments=[];Object.entries(p.loads).forEach(([id,list])=>list.forEach(a=>assignments.push({...a,press:data.presses.find(x=>x.id==id)})));$('#dashboard-assignments').innerHTML=assignments.sort((a,b)=>a.product.due.localeCompare(b.product.due)).map(a=>`<tr><td><b>${a.product.name}</b><br><span class="part">${a.product.part}</span></td><td>${a.product.due}</td><td>${a.press.name}</td><td>${hours(a.minutes)}</td><td><span class="status ${daysUntil(a.product.due)<=2?'alert':''}">${status(a.product)}</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Add products to build your schedule.</td></tr>'}
function renderProducts(){$('#products-table').innerHTML=data.products.map(p=>`<tr><td class="part">${p.part}</td><td><b>${p.name}</b></td><td>${p.assembly?`<b>${p.assembly}</b><br><span class="part">Assembly component</span>`:'<span class="part">Individual part</span>'}</td><td>${p.material}</td><td>${p.punch} / ${p.die}</td><td>${p.length} in</td><td>${p.qty}</td><td><button class="text-button edit-time" data-id="${p.id}">${p.avg.toFixed(1)} min</button></td><td>${p.due}</td><td><button class="text-button edit-product" data-id="${p.id}">Edit</button> <button class="text-button remove-product" data-id="${p.id}">Remove</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty">No products yet.</td></tr>';$$('.edit-time').forEach(b=>b.onclick=()=>{go('working-time');$('#time-product').value=b.dataset.id;$('#total-time').focus()});$$('.edit-product').forEach(b=>b.onclick=()=>openEditProduct(+b.dataset.id));$$('.remove-product').forEach(b=>b.onclick=()=>{data.products=data.products.filter(p=>p.id!==+b.dataset.id);save();renderAll()})}
function renderAssemblyFields(){let count=+$('#assembly-count').value;$('#assembly-component-fields').innerHTML=Array.from({length:count},(_,i)=>`<label>Part ${i+1} number<input class="assembly-component-part" required placeholder="BP-1042"></label><label>Qty per assembly<input class="assembly-component-qty" type="number" min="1" value="1" required></label>`).join('')}
function renderUncoded(kind='products'){let list=kind==='products'?data.uncodedProducts:data.uncodedAssemblies;$('#uncoded-list').innerHTML=list.length?list.map(item=>`<div class="list-row"><span><b>${item.part}</b><br><span class="part">Imported quantity: ${item.qty||'—'} · due ${item.due||'—'}</span></span><span><button class="text-button program-uncoded" data-kind="${kind}" data-part="${item.part}">Program</button>${kind==='products'?` <button class="text-button move-uncoded" data-part="${item.part}">Mark as assembly</button>`:''}</span></div>`).join(''):'<div class="empty">No uncoded ${kind}.</div>';$$('.move-uncoded').forEach(button=>button.onclick=()=>{let item=data.uncodedProducts.find(x=>x.part===button.dataset.part);data.uncodedProducts=data.uncodedProducts.filter(x=>x.part!==button.dataset.part);data.uncodedAssemblies.push(item);save();renderAll();renderUncoded('assemblies')});$$('.program-uncoded').forEach(button=>button.onclick=()=>{let item=(button.dataset.kind==='products'?data.uncodedProducts:data.uncodedAssemblies).find(x=>x.part===button.dataset.part);if(button.dataset.kind==='products'){resetProductForm();$('#part-number').value=item.part;$('#quantity').value=item.qty||1;$('#due-date').value=item.due||'2026-09-15';$('#product-dialog').showModal()}else{go('assemblies');$('#assembly-id').value=item.part;renderAssemblyFields()}})}
function renderAssemblies(){renderAssemblyFields();let ids=Object.keys(data.assemblies);$('#assembly-order-id').innerHTML=ids.map(id=>`<option>${id}</option>`).join('')||'<option value="">No assemblies programmed</option>';$('#assembly-list').innerHTML=ids.length?ids.map(id=>`<div class="assignment"><b>${id}</b><div class="assignment-meta">${data.assemblies[id].components.map(c=>`${c.part}: ${c.qty} per assembly`).join(' · ')}</div><div class="tool-pills">${data.assemblies[id].components.map(c=>`<button class="text-button remove-component" data-assembly="${id}" data-part="${c.part}">Remove ${c.part}</button>`).join('')}</div></div>`).join(''):'<div class="empty">Program components to create an assembly.</div>';$$('.remove-component').forEach(button=>button.onclick=()=>{let assembly=data.assemblies[button.dataset.assembly];assembly.components=assembly.components.filter(c=>c.part!==button.dataset.part);if(!assembly.components.length)delete data.assemblies[button.dataset.assembly];save();renderAll()});renderUncoded()}
function renderTimes(){$('#time-product').innerHTML=data.products.map(p=>`<option value="${p.id}">${p.part} — ${p.name} (${p.avg.toFixed(1)} min avg.)</option>`).join('');$('#time-history').innerHTML=data.history.length?data.history.slice(0,8).map(h=>`<div class="history-row"><span><b>${h.part}</b> updated from ${h.before.toFixed(1)} to <b>${h.after.toFixed(1)} min/part</b>${h.total?` · ${h.total} min ÷ ${h.qty} parts = ${h.observed.toFixed(1)} min/part`:''}${h.note?' · '+h.note:''}</span><span class="part">${h.when}</span></div>`).join(''):'<div class="empty">No time updates recorded yet.</div>'}
function renderTooling(){let punches=data.tooling.filter(t=>t.category==='punch'),dies=data.tooling.filter(t=>t.category==='die');$('#punch').innerHTML=punches.map(t=>`<option>${t.name}</option>`).join('');$('#die').innerHTML=dies.map(t=>`<option>${t.name}</option>`).join('');$('#tooling-table').innerHTML=data.tooling.map(t=>{let presses=data.presses.filter(p=>p.tools.includes(t.name)).map(p=>p.name).join(', ')||'Not assigned to a press';let lastOfType=data.tooling.filter(item=>item.category===t.category).length===1;return `<tr><td><b>${t.name}</b></td><td><span class="status">${t.category}</span></td><td>${presses}</td><td><button class="text-button delete-tool" data-tool="${t.name}" ${lastOfType?'disabled title="Keep at least one '+t.category+' in the library"':''}>Delete</button></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">No tooling programmed.</td></tr>';$$('.delete-tool').forEach(b=>b.onclick=()=>{let tool=b.dataset.tool,item=data.tooling.find(t=>t.name===tool),replacement=data.tooling.find(t=>t.category===item.category&&t.name!==tool);data.tooling=data.tooling.filter(t=>t.name!==tool);data.presses.forEach(p=>{p.tools=p.tools.filter(t=>t!==tool);if(!p.tools.some(name=>data.tooling.find(t=>t.name===name)?.category===item.category))p.tools.push(replacement.name)});data.products.forEach(p=>{if(p[item.category]===tool)p[item.category]=replacement.name});Object.values(data.partLibrary).forEach(p=>{if(p[item.category]===tool)p[item.category]=replacement.name});save();renderAll()})}
function renderPresses(){$('#press-cards').innerHTML=data.presses.map(p=>`<article class="press-card"><div class="press-head"><div><div class="press-name">${p.name}</div><div class="tool-pills">${p.materials.map(m=>`<span class="pill">${m}</span>`).join('')}</div></div><span class="status">${hours(p.daily)}/day · ${p.maxLength} in max</span></div><div class="press-controls"><label>Allowed run time / day (hours)<input class="daily" data-id="${p.id}" type="number" min="0.5" step="0.5" value="${p.daily/60}"></label><label>Maximum part length (in)<input class="max-length" data-id="${p.id}" type="number" min="0.1" step="0.1" value="${p.maxLength}"></label><div><p class="eyebrow">CURRENT PUNCH &amp; DIE</p><div class="tool-checks">${data.tooling.map(t=>{let onlyOne=p.tools.filter(name=>data.tooling.find(tool=>tool.name===name)?.category===t.category).length===1;return `<label><input class="tool-toggle" data-id="${p.id}" data-tool="${t.name}" type="checkbox" ${p.tools.includes(t.name)?'checked':''} ${p.tools.includes(t.name)&&onlyOne?'disabled':''}><span class="part">${t.category}</span> ${t.name}</label>`}).join('')}</div></div></div></article>`).join('');$$('.daily').forEach(i=>i.onchange=()=>{data.presses.find(p=>p.id==i.dataset.id).daily=Math.max(30,Math.round(+i.value*2)*30);save();renderAll()});$$('.max-length').forEach(i=>i.onchange=()=>{data.presses.find(p=>p.id==i.dataset.id).maxLength=Math.max(.1,+i.value);save();renderAll()});$$('.tool-toggle').forEach(i=>i.onchange=()=>{let p=data.presses.find(x=>x.id==i.dataset.id);p.tools=i.checked?[...new Set([...p.tools,i.dataset.tool])]:p.tools.filter(t=>t!==i.dataset.tool);save();renderAll()})}
function renderSchedule(){let p=plan();$('#schedule-grid').innerHTML=data.presses.map(press=>{let list=p.loads[press.id],used=list.reduce((n,a)=>n+a.minutes,0);return `<article class="schedule-card"><div class="panel-title"><div><h3>${press.name}</h3><div class="schedule-capacity">${hours(used)} scheduled / ${hours(press.daily)} allowed daily</div></div><button class="button print-press" data-id="${press.id}">Print checklist</button></div>${list.length?list.map(a=>`<div class="assignment"><b>${a.product.name}</b><div class="assignment-meta">${a.product.part}${a.product.assembly?` · Assembly ${a.product.assembly}`:' · Individual part'}<br>${a.product.qty} pcs · Punch: ${a.product.punch} · Die: ${a.product.die} · ${hours(a.minutes)}</div></div>`).join(''):'<div class="empty">No compatible jobs assigned.</div>'}</article>`}).join('')+(p.un.length?`<article class="schedule-card unassigned"><h3>Deferred work</h3>${p.un.map(a=>`<div class="assignment"><b>${a.product.name}</b><div class="assignment-meta">${a.product.part} · due ${a.product.due}<br>${a.reason}</div></div>`).join('')}</article>`:'');$$('.print-press').forEach(b=>b.onclick=()=>printPress(+b.dataset.id))}
function renderDue(){let p=plan(), ids=new Set(Object.values(p.loads).flat().map(a=>a.product.id));$('#due-table').innerHTML=[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).map(x=>`<tr><td><span class="status ${daysUntil(x.due)<=2?'alert':''}">${x.due} · ${daysUntil(x.due)}d</span></td><td><b>${x.name}</b></td><td class="part">${x.part}</td><td>${x.qty}</td><td>${hours(est(x))}</td><td>${ids.has(x.id)?'Assigned':'Needs review'}</td></tr>`).join('')}
function go(id){$$('.tab,.nav-item').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');$(`.nav-item[data-tab="${id}"]`).classList.add('active');let title={dashboard:'Today’s production plan',products:'Product library',assemblies:'Assembly builder',"working-time":'Working time',tooling:'Tooling library',presses:'Brake presses',schedule:'Automatic schedule',weekly:'Weekly schedule',capacity:'Capacity planning',import:'Import schedule',"due-dates":'Upcoming due dates'}[id];$('#page-title').textContent=title;$('#section-label').textContent=id.replace('-', ' ').toUpperCase()}
let editingProductId=null;
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));function resetProductForm(){let form=$('#product-form');form.reset();editingProductId=null;$('#product-dialog-title').textContent='Program a new part';$('#save-product').textContent='Save product';setAssemblyField();$('#due-date').value='2026-09-15'}function openEditProduct(id){let p=data.products.find(product=>product.id===id);if(!p)return;editingProductId=id;$('#product-dialog-title').textContent='Edit product';$('#save-product').textContent='Save changes';$('#part-number').value=p.part;$('#product-name').value=p.name;$('#product-type').value=p.assembly?'assembly':'individual';$('#assembly-number').value=p.assembly||'';$('#material').value=p.material;$('#punch').value=p.punch;$('#die').value=p.die;$('#part-length').value=p.length;$('#quantity').value=p.qty;$('#avg-time').value=p.avg;$('#due-date').value=p.due;setAssemblyField();$('#product-dialog').showModal()}$('#quick-product').onclick=()=>{resetProductForm();$('#product-dialog').showModal()};$('#add-product').onclick=()=>{$('#quick-add-form').reset();$('#quick-add-error').hidden=true;$('#quick-due-date').value='2026-09-15';$('#quick-add-dialog').showModal()};$('#run-schedule').onclick=()=>{renderAll();$('#run-schedule').textContent='✓ Schedule updated';setTimeout(()=>$('#run-schedule').textContent='↯ Build schedule',1200)};
$('#time-form').onsubmit=e=>{e.preventDefault();let p=data.products.find(p=>p.id==+$('#time-product').value),total=+$('#total-time').value,qty=+$('#sample-qty').value,observed=total/qty,before=p.avg;p.avg=((p.avg*p.qty)+(observed*qty))/(p.qty+qty);data.products.filter(job=>job.part===p.part).forEach(job=>job.avg=p.avg);if(data.partLibrary[p.part])data.partLibrary[p.part].avg=p.avg;data.history.unshift({part:p.part,before,after:p.avg,total,qty,observed,note:$('#time-note').value,when:new Date().toLocaleDateString()});save();e.target.reset();$('#sample-qty').value=1;renderAll()};
function setAssemblyField(){let assembly=$('#product-type').value==='assembly';$('#assembly-field').hidden=!assembly;$('#assembly-number').required=assembly;if(!assembly)$('#assembly-number').value=''}
$('#product-type').onchange=setAssemblyField;
$$('.cancel-product').forEach(button=>button.onclick=()=>$('#product-dialog').close());
$('#product-form').onsubmit=e=>{e.preventDefault();let p={id:editingProductId||Date.now(),part:$('#part-number').value.trim().toUpperCase(),name:$('#product-name').value,assembly:$('#product-type').value==='assembly'?$('#assembly-number').value.trim():null,material:$('#material').value,punch:$('#punch').value,die:$('#die').value,length:+$('#part-length').value,qty:+$('#quantity').value,avg:+$('#avg-time').value,due:$('#due-date').value};let index=data.products.findIndex(job=>job.id===editingProductId);if(index>=0)data.products[index]=p;else data.products.push(p);data.partLibrary[p.part]={part:p.part,name:p.name,assembly:p.assembly||null,material:p.material,punch:p.punch,die:p.die,length:p.length,qty:p.qty,avg:p.avg};save();$('#product-dialog').close();renderAll();go('products')};
$$('.cancel-quick').forEach(button=>button.onclick=()=>$('#quick-add-dialog').close());$('#quick-add-form').onsubmit=e=>{e.preventDefault();let part=$('#quick-part-number').value.trim().toUpperCase(),template=data.partLibrary[part],error=$('#quick-add-error');if(!template){error.textContent='That part has not been programmed yet. Use New Product to enter its full information.';error.hidden=false;return}let p={...template,id:Date.now(),due:$('#quick-due-date').value};data.products.push(p);save();$('#quick-add-dialog').close();renderAll();go('products')};
$('#tool-form').onsubmit=e=>{e.preventDefault();let name=$('#new-tool').value.trim(),category=$('#tool-category').value;if(name&&!data.tooling.some(t=>t.name.toLowerCase()===name.toLowerCase())){data.tooling.push({name,category});save();e.target.reset();renderAll()}};
importRows=function(rows){let added=0,updated=0,uncoded=0;function addPart(part,qty,due,assembly){let template=data.partLibrary[part];if(!template){if(!data.uncodedProducts.some(item=>item.part===part))data.uncodedProducts.push({part,qty,due});uncoded++;return}let existing=data.products.find(job=>job.part===part&&job.due===due&&job.assembly===(assembly||null));if(existing){existing.qty=qty;updated++}else{data.products.push({...template,id:Date.now()+added,qty,due,assembly:assembly||null});added++}}rows.forEach(row=>{let fields=Object.fromEntries(Object.entries(row).map(([k,v])=>[normalizeHeader(k),v])),number=String(fields.partnumber||fields.part||fields.itemnumber||fields.assemblynumber||'').trim().toUpperCase();if(!number)return;let due=fields.duedate||fields.duedateplanned||fields.promisedate||fields.deliverydate||'';if(typeof due==='number'&&window.XLSX)due=XLSX.SSF.format('yyyy-mm-dd',due);due=String(due).slice(0,10)||'2026-09-15';let qty=Number(fields.quantity||fields.qty||1)||1,assembly=data.assemblies[number];if(assembly){assembly.components.forEach(component=>addPart(component.part,component.qty*qty,due,number));return}if(data.partLibrary[number]){addPart(number,qty,due,fields.assemblynumber||fields.assembly||null);return}let isAssembly=/assembly|asm/i.test(String(fields.type||fields.itemtype||number));let queue=isAssembly?data.uncodedAssemblies:data.uncodedProducts;if(!queue.some(item=>item.part===number))queue.push({part:number,qty,due});uncoded++});save();$('#import-result').innerHTML=`<div class="history-row"><span><b>${added}</b> scheduled parts added · <b>${updated}</b> jobs updated</span><span class="part">Import complete</span></div><div class="history-row"><span><b>${uncoded}</b> uncoded numbers sent to Products for review</span></div>`;renderAll()};
$('#assembly-count').onchange=renderAssemblyFields;$$('.uncoded-tab').forEach(button=>button.onclick=()=>{$$('.uncoded-tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderUncoded(button.dataset.uncoded)});$('#assembly-component-form').onsubmit=e=>{e.preventDefault();let id=$('#assembly-id').value.trim().toUpperCase(),parts=$$('.assembly-component-part'),qtys=$$('.assembly-component-qty');if(!id)return;let components=[];parts.forEach((input,i)=>{let part=input.value.trim().toUpperCase(),qty=Math.max(1,+qtys[i].value);if(!part)return;components.push({part,qty});if(!data.partLibrary[part]&&!data.uncodedProducts.some(item=>item.part===part))data.uncodedProducts.push({part,qty:null,due:null})});if(!components.length)return;data.assemblies[id]={components};data.uncodedAssemblies=data.uncodedAssemblies.filter(item=>item.part!==id);save();e.target.reset();renderAll()};
$('#assembly-order-form').onsubmit=e=>{e.preventDefault();let id=$('#assembly-order-id').value,units=Math.max(1,+$('#assembly-order-qty').value),due=$('#assembly-order-due').value,assembly=data.assemblies[id];if(!assembly||!due)return;assembly.components.forEach(component=>{let template=data.partLibrary[component.part];if(template)data.products.push({...template,id:Date.now()+data.products.length,qty:component.qty*units,due,assembly:id})});save();renderAll();go('products')};
$('#build-weekly').onclick=()=>renderWeekly();$('#run-capacity').onclick=()=>renderCapacity();$('#import-schedule').onclick=()=>{let file=$('#import-file').files[0],result=$('#import-result');if(!file){result.innerHTML='<div class="empty">Choose an Excel or CSV file first.</div>';return}let reader=new FileReader();reader.onload=event=>{try{let rows;if(file.name.toLowerCase().endsWith('.csv')){let lines=String(event.target.result).split(/\r?\n/).filter(Boolean),headers=lines.shift().split(',').map(x=>x.trim());rows=lines.map(line=>Object.fromEntries(line.split(',').map((value,i)=>[headers[i],value.trim()])))}else{if(!window.XLSX)throw new Error('Excel reader is still loading. Try again in a moment.');let book=XLSX.read(event.target.result,{type:'array'});rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''})}importRows(rows)}catch(error){result.innerHTML=`<div class="empty">Could not read that file: ${error.message}</div>`}};if(file.name.toLowerCase().endsWith('.csv'))reader.readAsText(file);else reader.readAsArrayBuffer(file)};
function setLoginMessage(message,ok=false){let el=$('#login-message');el.textContent=message||'';el.classList.toggle('ok',ok)}
function setCurrentUser(user){let name=user?.user_metadata?.full_name||user?.email||'A+J production planning';$('#current-user').textContent=name}
function showLogin(message=''){cloudReady=false;currentSession=null;$('#login-screen').hidden=false;if(message)setLoginMessage(message)}
async function syncWorkspace(){if(!cloudReady||!currentSession)return;let name=currentSession.user.user_metadata?.full_name||currentSession.user.email;let result=await cloud.from('pressflow_data').upsert({id:1,data,updated_by:currentSession.user.id,updated_by_name:name,updated_at:new Date().toISOString()},{onConflict:'id'});if(result.error)console.warn('Shared save failed:',result.error.message)}
async function openWorkspace(session){currentSession=session;setCurrentUser(session.user);let result=await cloud.from('pressflow_data').select('data,updated_by_name,updated_at').eq('id',1).maybeSingle();if(result.error){showLogin(`The shared database needs setup: ${result.error.message}`);return}cloudReady=true;$('#login-screen').hidden=true;if(result.data?.data&&typeof result.data.data==='object'){data=result.data.data;localStorage.setItem(key,JSON.stringify(data));}else await syncWorkspace();renderAll();if(workspaceChannel)cloud.removeChannel(workspaceChannel);workspaceChannel=cloud.channel('pressflow-workspace').on('postgres_changes',{event:'UPDATE',schema:'public',table:'pressflow_data',filter:'id=eq.1'},payload=>{if(payload.new.updated_by===currentSession?.user?.id)return;if(payload.new.data&&typeof payload.new.data==='object'){data=payload.new.data;localStorage.setItem(key,JSON.stringify(data));renderAll()}}).subscribe()}
async function initializeCloud(){if(!cloud){showLogin('Unable to load the secure sign-in service. Refresh and try again.');return}let {data:sessionData}=await cloud.auth.getSession();if(sessionData.session)await openWorkspace(sessionData.session);else showLogin();cloud.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT')showLogin();if((event==='SIGNED_IN'||event==='TOKEN_REFRESHED')&&session&&!cloudReady)await openWorkspace(session)})}
$('#login-form').onsubmit=async event=>{event.preventDefault();setLoginMessage('Signing in…',true);let result=await cloud.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(result.error){setLoginMessage(result.error.message);return}await openWorkspace(result.data.session)};
$('#signup-form').onsubmit=async event=>{event.preventDefault();if($('#signup-code').value!==TEMPORARY_EMPLOYEE_CODE){setLoginMessage('That employee access code is not correct.');return}setLoginMessage('Creating your account…',true);let result=await cloud.auth.signUp({email:$('#signup-email').value.trim(),password:$('#signup-password').value,options:{data:{full_name:$('#signup-name').value.trim()}}});if(result.error){setLoginMessage(result.error.message);return}if(result.data.session)await openWorkspace(result.data.session);else setLoginMessage('Check your email to confirm your account, then return here to sign in.',true)};
$('#sign-out').onclick=async()=>{if(cloud)await cloud.auth.signOut()};
$('#today').textContent=today().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});$('#due-date').value='2026-09-15';$('#assembly-order-due').value='2026-09-15';renderAll();initializeCloud();
