const key='pressflow-data-v1';
const defaultTools=[{name:'Gooseneck',category:'punch'},{name:'Hemming',category:'punch'},{name:'V-die 1/2 in',category:'die'},{name:'V-die 1 in',category:'die'}];
const seed={products:[
 {id:1,part:'BP-1042',name:'Mounting bracket',material:'Steel',tool:'V-die 1/2 in',qty:180,avg:2.8,due:'2026-09-10'},
 {id:2,part:'PX-8810',name:'Enclosure side panel',material:'Stainless steel',tool:'Gooseneck',qty:55,avg:6.2,due:'2026-09-11'},
 {id:3,part:'AL-2007',name:'Control box lid',material:'Aluminum',tool:'V-die 1 in',qty:120,avg:3.6,due:'2026-09-15'},
 {id:4,part:'BP-1058',name:'Angle support',material:'Steel',tool:'Hemming',qty:240,avg:1.9,due:'2026-09-18'},
 {id:5,part:'SS-4150',name:'Guard rail plate',material:'Stainless steel',tool:'V-die 1 in',qty:70,avg:5.1,due:'2026-09-20'}],
 presses:[
 {id:1,name:'Press 1',daily:420,materials:['Steel','Aluminum'],tools:['V-die 1/2 in','V-die 1 in']},
 {id:2,name:'Press 2',daily:390,materials:['Steel','Stainless steel'],tools:['Gooseneck','V-die 1 in']},
 {id:3,name:'Press 3',daily:450,materials:['Aluminum','Steel'],tools:['V-die 1/2 in','Hemming','V-die 1 in']},
 {id:4,name:'Press 4',daily:360,materials:['Stainless steel','Steel'],tools:['Gooseneck','Hemming']}],history:[],tooling:defaultTools,partLibrary:{}};
let data=JSON.parse(localStorage.getItem(key))||seed;
if(!Array.isArray(data.tooling))data.tooling=[...defaultTools];
data.tooling=data.tooling.map(t=>typeof t==='string'?{name:t,category:/die/i.test(t)?'die':'punch'}:t);
if(!data.partLibrary)data.partLibrary={};
data.products.forEach(p=>{let oldTool=p.tool;if(!p.punch)p.punch=data.tooling.find(t=>t.category==='punch'&&t.name===oldTool)?.name||data.tooling.find(t=>t.category==='punch')?.name;if(!p.die)p.die=data.tooling.find(t=>t.category==='die'&&t.name===oldTool)?.name||data.tooling.find(t=>t.category==='die')?.name;if(!data.partLibrary[p.part])data.partLibrary[p.part]={part:p.part,name:p.name,assembly:p.assembly||null,material:p.material,punch:p.punch,die:p.die,qty:p.qty,avg:p.avg}});
Object.values(data.partLibrary).forEach(p=>{if(!p.punch)p.punch=data.tooling.find(t=>t.category==='punch')?.name;if(!p.die)p.die=data.tooling.find(t=>t.category==='die')?.name});
data.presses.forEach(press=>['punch','die'].forEach(category=>{if(!press.tools.some(name=>data.tooling.find(t=>t.name===name)?.category===category)){let tool=data.tooling.find(t=>t.category===category)?.name;if(tool)press.tools.push(tool)}}));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(key,JSON.stringify(data))} function hours(min){return `${(min/60).toFixed(1)} hr`} function est(p){return p.qty*p.avg}
function printPress(id){let press=data.presses.find(p=>p.id===id),list=plan().loads[id],used=list.reduce((n,a)=>n+a.minutes,0),w=window.open('','_blank','width=850,height=700');if(!w)return;w.document.write(`<!doctype html><html><head><title>${press.name} checklist</title><style>body{font-family:Arial,sans-serif;color:#102a43;margin:36px}h1{margin:0}p{color:#526b80}.meta{border-top:2px solid #126db5;border-bottom:1px solid #cbddeb;padding:12px 0;margin:18px 0;font-size:14px}table{width:100%;border-collapse:collapse}th{text-align:left;background:#eaf5ff;color:#0a3f6b;padding:10px;font-size:12px}td{border-bottom:1px solid #d8e5f0;padding:13px 10px;font-size:13px}.check{width:28px;height:28px;border:2px solid #126db5;border-radius:4px}.assembly{font-weight:bold;color:#126db5}@media print{body{margin:18px}}</style></head><body><h1>Press Flow — ${press.name}</h1><p>A+J Design LLC · Production checklist</p><div class="meta"><b>Scheduled work:</b> ${hours(used)} &nbsp; | &nbsp; <b>Allowed daily run time:</b> ${hours(press.daily)} &nbsp; | &nbsp; <b>Printed:</b> ${new Date().toLocaleDateString()}</div><table><thead><tr><th>Done</th><th>Part number</th><th>Assembly number</th><th>Product</th><th>Quantity</th><th>Punch / die</th><th>Est. time</th></tr></thead><tbody>${list.map(a=>`<tr><td><div class="check"></div></td><td>${a.product.part}</td><td class="assembly">${a.product.assembly||'Individual part'}</td><td>${a.product.name}</td><td>${a.product.qty}</td><td>${a.product.punch} / ${a.product.die}</td><td>${hours(a.minutes)}</td></tr>`).join('')||'<tr><td colspan="7">No assignments scheduled.</td></tr>'}</tbody></table></body></html>`);w.document.close();w.focus();w.print()}
function today(){return new Date('2026-09-08T12:00:00')} function daysUntil(date){return Math.ceil((new Date(date+'T12:00:00')-today())/86400000)}
function status(p){let d=daysUntil(p.due);return d<=2?'Due soon':d<=7?'This week':'Upcoming'}
function compatible(p,press){return press.materials.includes(p.material)&&press.tools.includes(p.punch)&&press.tools.includes(p.die)}
function plan(){let loads=Object.fromEntries(data.presses.map(p=>[p.id,[]]));let un=[];[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).forEach(product=>{let compatiblePresses=data.presses.filter(press=>compatible(product,press)).map(press=>{let used=loads[press.id].reduce((n,a)=>n+a.minutes,0);let grouped=product.assembly&&loads[press.id].some(a=>a.product.assembly===product.assembly);return {press,used,score:used/press.daily-(grouped ? 0.18 : 0)}}).sort((a,b)=>a.score-b.score);if(!compatiblePresses.length){un.push({product,reason:'No compatible press'});return}let best=compatiblePresses.find(candidate=>candidate.used+est(product)<=candidate.press.daily);if(!best){un.push({product,reason:'Deferred — later due date than work already scheduled'});return}loads[best.press.id].push({product,minutes:est(product),over:false})});return {loads,un}}
function renderAll(){renderDashboard();renderProducts();renderTimes();renderTooling();renderPresses();renderSchedule();renderDue()}
function renderDashboard(){let p=plan(), assigned=Object.values(p.loads).flat().length, total=data.products.reduce((n,x)=>n+est(x),0), capacity=data.presses.reduce((n,x)=>n+x.daily,0), soon=data.products.filter(x=>daysUntil(x.due)<=7).length;$('#metrics').innerHTML=[['Open products',data.products.length,'ready to schedule'],['Estimated work',hours(total),'across all products'],['Daily capacity',hours(capacity),'four brake presses'],['Due within 7 days',soon,soon?'priority assignments':'no urgent work']].map(x=>`<div class="metric"><div class="metric-value">${x[1]}</div><div class="metric-note">${x[0]} · ${x[2]}</div></div>`).join('');$('#utilization').innerHTML=data.presses.map(press=>{let used=(p.loads[press.id]||[]).reduce((n,a)=>n+a.minutes,0),pct=Math.round(100*used/press.daily);return `<div class="progress-row"><span>${press.name}</span><div class="track"><div class="fill ${pct>100?'over':''}" style="width:${Math.min(pct,100)}%"></div></div><b>${pct}%</b></div>`}).join('');$('#due-soon').innerHTML=[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4).map(x=>`<div class="list-row"><span><b>${x.name}</b><br><span class="part">${x.part}</span></span><span class="due-tag ${daysUntil(x.due)<=2?'hot':''}">${daysUntil(x.due)}d · ${x.due.slice(5)}</span></div>`).join('');let assignments=[];Object.entries(p.loads).forEach(([id,list])=>list.forEach(a=>assignments.push({...a,press:data.presses.find(x=>x.id==id)})));$('#dashboard-assignments').innerHTML=assignments.sort((a,b)=>a.product.due.localeCompare(b.product.due)).map(a=>`<tr><td><b>${a.product.name}</b><br><span class="part">${a.product.part}</span></td><td>${a.product.due}</td><td>${a.press.name}</td><td>${hours(a.minutes)}</td><td><span class="status ${daysUntil(a.product.due)<=2?'alert':''}">${status(a.product)}</span></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Add products to build your schedule.</td></tr>'}
function renderProducts(){$('#products-table').innerHTML=data.products.map(p=>`<tr><td class="part">${p.part}</td><td><b>${p.name}</b></td><td>${p.assembly?`<b>${p.assembly}</b><br><span class="part">Assembly component</span>`:'<span class="part">Individual part</span>'}</td><td>${p.material}</td><td>${p.punch} / ${p.die}</td><td>${p.qty}</td><td><button class="text-button edit-time" data-id="${p.id}">${p.avg.toFixed(1)} min</button></td><td>${p.due}</td><td><button class="text-button remove-product" data-id="${p.id}">Remove</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No products yet.</td></tr>';$$('.edit-time').forEach(b=>b.onclick=()=>{go('working-time');$('#time-product').value=b.dataset.id;$('#observed-time').focus()});$$('.remove-product').forEach(b=>b.onclick=()=>{data.products=data.products.filter(p=>p.id!==+b.dataset.id);save();renderAll()})}
function renderTimes(){$('#time-product').innerHTML=data.products.map(p=>`<option value="${p.id}">${p.part} — ${p.name} (${p.avg.toFixed(1)} min avg.)</option>`).join('');$('#time-history').innerHTML=data.history.length?data.history.slice(0,8).map(h=>`<div class="history-row"><span><b>${h.part}</b> updated from ${h.before.toFixed(1)} to <b>${h.after.toFixed(1)} min/part</b>${h.note?' · '+h.note:''}</span><span class="part">${h.when}</span></div>`).join(''):'<div class="empty">No time updates recorded yet.</div>'}
function renderTooling(){let punches=data.tooling.filter(t=>t.category==='punch'),dies=data.tooling.filter(t=>t.category==='die');$('#punch').innerHTML=punches.map(t=>`<option>${t.name}</option>`).join('');$('#die').innerHTML=dies.map(t=>`<option>${t.name}</option>`).join('');$('#tooling-table').innerHTML=data.tooling.map(t=>{let presses=data.presses.filter(p=>p.tools.includes(t.name)).map(p=>p.name).join(', ')||'Not assigned to a press';let lastOfType=data.tooling.filter(item=>item.category===t.category).length===1;return `<tr><td><b>${t.name}</b></td><td><span class="status">${t.category}</span></td><td>${presses}</td><td><button class="text-button delete-tool" data-tool="${t.name}" ${lastOfType?'disabled title="Keep at least one '+t.category+' in the library"':''}>Delete</button></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">No tooling programmed.</td></tr>';$$('.delete-tool').forEach(b=>b.onclick=()=>{let tool=b.dataset.tool,item=data.tooling.find(t=>t.name===tool),replacement=data.tooling.find(t=>t.category===item.category&&t.name!==tool);data.tooling=data.tooling.filter(t=>t.name!==tool);data.presses.forEach(p=>{p.tools=p.tools.filter(t=>t!==tool);if(!p.tools.some(name=>data.tooling.find(t=>t.name===name)?.category===item.category))p.tools.push(replacement.name)});data.products.forEach(p=>{if(p[item.category]===tool)p[item.category]=replacement.name});Object.values(data.partLibrary).forEach(p=>{if(p[item.category]===tool)p[item.category]=replacement.name});save();renderAll()})}
function renderPresses(){$('#press-cards').innerHTML=data.presses.map(p=>`<article class="press-card"><div class="press-head"><div><div class="press-name">${p.name}</div><div class="tool-pills">${p.materials.map(m=>`<span class="pill">${m}</span>`).join('')}</div></div><span class="status">${hours(p.daily)}/day</span></div><div class="press-controls"><label>Allowed run time / day (hours)<input class="daily" data-id="${p.id}" type="number" min="0.5" step="0.5" value="${p.daily/60}"></label><div><p class="eyebrow">CURRENT PUNCH &amp; DIE</p><div class="tool-checks">${data.tooling.map(t=>{let onlyOne=p.tools.filter(name=>data.tooling.find(tool=>tool.name===name)?.category===t.category).length===1;return `<label><input class="tool-toggle" data-id="${p.id}" data-tool="${t.name}" type="checkbox" ${p.tools.includes(t.name)?'checked':''} ${p.tools.includes(t.name)&&onlyOne?'disabled':''}><span class="part">${t.category}</span> ${t.name}</label>`}).join('')}</div></div></div></article>`).join('');$$('.daily').forEach(i=>i.onchange=()=>{data.presses.find(p=>p.id==i.dataset.id).daily=Math.max(30,Math.round(+i.value*2)*30);save();renderAll()});$$('.tool-toggle').forEach(i=>i.onchange=()=>{let p=data.presses.find(x=>x.id==i.dataset.id);p.tools=i.checked?[...new Set([...p.tools,i.dataset.tool])]:p.tools.filter(t=>t!==i.dataset.tool);save();renderAll()})}
function renderSchedule(){let p=plan();$('#schedule-grid').innerHTML=data.presses.map(press=>{let list=p.loads[press.id],used=list.reduce((n,a)=>n+a.minutes,0);return `<article class="schedule-card"><div class="panel-title"><div><h3>${press.name}</h3><div class="schedule-capacity">${hours(used)} scheduled / ${hours(press.daily)} allowed daily</div></div><button class="button print-press" data-id="${press.id}">Print checklist</button></div>${list.length?list.map(a=>`<div class="assignment"><b>${a.product.name}</b><div class="assignment-meta">${a.product.part}${a.product.assembly?` · Assembly ${a.product.assembly}`:' · Individual part'}<br>${a.product.qty} pcs · Punch: ${a.product.punch} · Die: ${a.product.die} · ${hours(a.minutes)}</div></div>`).join(''):'<div class="empty">No compatible jobs assigned.</div>'}</article>`}).join('')+(p.un.length?`<article class="schedule-card unassigned"><h3>Deferred work</h3>${p.un.map(a=>`<div class="assignment"><b>${a.product.name}</b><div class="assignment-meta">${a.product.part} · due ${a.product.due}<br>${a.reason}</div></div>`).join('')}</article>`:'');$$('.print-press').forEach(b=>b.onclick=()=>printPress(+b.dataset.id))}
function renderDue(){let p=plan(), ids=new Set(Object.values(p.loads).flat().map(a=>a.product.id));$('#due-table').innerHTML=[...data.products].sort((a,b)=>a.due.localeCompare(b.due)).map(x=>`<tr><td><span class="status ${daysUntil(x.due)<=2?'alert':''}">${x.due} · ${daysUntil(x.due)}d</span></td><td><b>${x.name}</b></td><td class="part">${x.part}</td><td>${x.qty}</td><td>${hours(est(x))}</td><td>${ids.has(x.id)?'Assigned':'Needs review'}</td></tr>`).join('')}
function go(id){$$('.tab,.nav-item').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');$(`.nav-item[data-tab="${id}"]`).classList.add('active');let title={dashboard:'Today’s production plan',products:'Product library',"working-time":'Working time',tooling:'Tooling library',presses:'Brake presses',schedule:'Automatic schedule',"due-dates":'Upcoming due dates'}[id];$('#page-title').textContent=title;$('#section-label').textContent=id.replace('-', ' ').toUpperCase()}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));function resetProductForm(){let form=$('#product-form');form.reset();$$('#product-form input,#product-form select').forEach(x=>x.disabled=false);$('#existing-product-note').hidden=true;setAssemblyField();$('#due-date').value='2026-09-15'}$('#quick-product').onclick=$('#add-product').onclick=()=>{resetProductForm();$('#product-dialog').showModal()};$('#run-schedule').onclick=()=>{renderAll();$('#run-schedule').textContent='✓ Schedule updated';setTimeout(()=>$('#run-schedule').textContent='↯ Build schedule',1200)};
$('#time-form').onsubmit=e=>{e.preventDefault();let p=data.products.find(p=>p.id==+$('#time-product').value), observed=+$('#observed-time').value,qty=+$('#sample-qty').value,before=p.avg; p.avg=((p.avg*p.qty)+(observed*qty))/(p.qty+qty);if(data.partLibrary[p.part])data.partLibrary[p.part].avg=p.avg;data.history.unshift({part:p.part,before,after:p.avg,note:$('#time-note').value,when:new Date().toLocaleDateString()});save();e.target.reset();$('#sample-qty').value=1;renderAll()};
function setAssemblyField(){let assembly=$('#product-type').value==='assembly';$('#assembly-field').hidden=!assembly;$('#assembly-number').required=assembly;if(!assembly)$('#assembly-number').value=''}
$('#product-type').onchange=setAssemblyField;
$$('.cancel-product').forEach(button=>button.onclick=()=>$('#product-dialog').close());
$('#part-number').oninput=()=>{let template=data.partLibrary[$('#part-number').value.trim().toUpperCase()],found=!!template;['product-name','product-type','assembly-number','material','punch','die','quantity','avg-time'].forEach(id=>$('#'+id).disabled=found);$('#existing-product-note').hidden=!found;if(!found)return;$('#product-name').value=template.name;$('#product-type').value=template.assembly?'assembly':'individual';$('#assembly-number').value=template.assembly||'';$('#material').value=template.material;$('#punch').value=template.punch;$('#die').value=template.die;$('#quantity').value=template.qty;$('#avg-time').value=template.avg;setAssemblyField();$('#assembly-number').disabled=true};
$('#product-form').onsubmit=e=>{e.preventDefault();let part=$('#part-number').value.trim().toUpperCase(),template=data.partLibrary[part],p=template?{...template,id:Date.now(),due:$('#due-date').value}:{id:Date.now(),part,name:$('#product-name').value,assembly:$('#product-type').value==='assembly'?$('#assembly-number').value.trim():null,material:$('#material').value,punch:$('#punch').value,die:$('#die').value,qty:+$('#quantity').value,avg:+$('#avg-time').value,due:$('#due-date').value};data.products.push(p);data.partLibrary[part]={part:p.part,name:p.name,assembly:p.assembly||null,material:p.material,punch:p.punch,die:p.die,qty:p.qty,avg:p.avg};save();$('#product-dialog').close();renderAll();go('products')};
$('#tool-form').onsubmit=e=>{e.preventDefault();let name=$('#new-tool').value.trim(),category=$('#tool-category').value;if(name&&!data.tooling.some(t=>t.name.toLowerCase()===name.toLowerCase())){data.tooling.push({name,category});save();e.target.reset();renderAll()}};
$('#today').textContent=today().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});$('#due-date').value='2026-09-15';renderAll();
